- hosts: terraform-ansible
  tasks:
    - name: Install python 3, setuptools and virtualenv
      apt:
        pkg:
          - python3
          - python3-setuptools
          - virtualenv
        update_cache: yes
      become: yes
    - name: Remove old project
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /home/ubuntu/test
      ignore_errors: yes
    - name: Git Clone
      ansible.builtin.git:
        repo: https://github.com/guilhermeonrails/clientes-leo-api.git
        dest: /home/ubuntu/test
        version: master
        force: yes
    - name: Dependencies install with pip (Django and Django Rest)
      pip:
        virtualenv: /home/ubuntu/venv
        requirements: /home/ubuntu/test/requirements.txt
    - name: Changing hosts settings
      lineinfile:
        path: /home/ubuntu/test/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
    - name: Run migrates on database
      shell: ". /home/ubuntu/venv/bin/activate; python /home/ubuntu/test/manage.py migrate"
    - name: Load inicial data
      shell: ". /home/ubuntu/venv/bin/activate; python /home/ubuntu/test/manage.py loaddata clientes.json"
    - name: Start server
      shell: ". /home/ubuntu/venv/bin/activate; nohup python /home/ubuntu/test/manage.py runserver 0.0.0.0:8000 &"
